---
me: vinod
my_email: vinod@kurup.com

# weareinteractive.users
users:
  - username: "{{ me }}"
    authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGzbDE3xqnCZOfJF/MhgYRyq4cach264SdQZ0ntoPB1U vkurup@caktus020"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID5c3EtrrwEOwMfv5d6VyntdGsS2kRyWTKl26vqx7R0y vinod@kurup.com"
    shell: "/bin/bash"

# weareinteractive.sudo
sudo_users:
  - name: "{{ me }}"
    nopasswd: yes
purge_other_sudoers_files: yes

# geerlingguy.security
security_autoupdate_mail_to: "{{ my_email }}"
security_fail2ban_custom_configuration_template: "vkjail.local.j2"
# geerlingguy.security does sudo settings, but we use the sudo role above for that

# geerlingguy.pip
pip_install_packages:
  - name: docker
  - name: docker-compose

# geerlingguy.docker
docker_users:
  - "{{ me }}"


# localrole: swag
domain: drkurup.com
subdomains: "www,syncthing"
swag_email: "{{ my_email }}"

# localrole: rss2email
r2e_config_path: "/opt/appdata/syncthing/data/vinod-dropbox/data/rss2email.cfg"
r2e_data_path: "/opt/appdata/syncthing/data/vinod-dropbox/data/rss2email.json"
