---
- hosts: do1
  become: yes
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - geerlingguy.postfix
    - base
    - swag
    - syncthing
    - calibre-web
    - rss2email
    - countdown

- hosts:
    - nodevps1
    - nodevps2
  become: yes
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - geerlingguy.postfix
