---
- name: Install base packages
  apt:
    pkg:
    - htop
    - net-tools

- name: Monitor uptime
  cron:
    user: "{{ app_user }}"
    name: "check uptime"
    minute: "1"
    job: "curl -fsS --retry 5 -o /dev/null {{ connectivity_hc_url }}"
